export const SeriesData = {
  peringkat: "1",
  judul: "Spiderman Makan Lontong",
  sinopsisfilm: "Peter Parker mencoba makan lontong dan menghadapi musuh baru.",
  urlfilm: "https://www.youtube.com/watch?v=abcdefghijk",
  tanggalRilisfilm: "2024-04-30",
  totalView: 10000000,
  jenis: "series",
  sutradara: "Jon Doe",
  pemain: ["Tom Holland", "Zendaya"],
  asalNegara: "Amerika Serikat",
  jumlahEpisode: 10,
  episode: [
    { nomor: 1, link: "https://www.youtube.com/watch?v=episode1" },
    { nomor: 2, link: "https://www.youtube.com/watch?v=episode2" },
    { nomor: 3, link: "https://www.youtube.com/watch?v=episode3" },
    { nomor: 4, link: "https://www.youtube.com/watch?v=episode4" },
    { nomor: 5, link: "https://www.youtube.com/watch?v=episode5" },
    { nomor: 6, link: "https://www.youtube.com/watch?v=episode6" },
    { nomor: 7, link: "https://www.youtube.com/watch?v=episode7" },
    { nomor: 8, link: "https://www.youtube.com/watch?v=episode8" },
    { nomor: 9, link: "https://www.youtube.com/watch?v=episode9" },
    { nomor: 10, link: "https://www.youtube.com/watch?v=episode10" }
  ],
  genre: ["Action", "Adventure", "Comedy"],
  penulisSkenario: ["John Smith", "Jane Doe"],
}